# Generated by Django 5.1 on 2024-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
