# Generated by Django 5.1 on 2024-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0003_alter_client_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
