# Generated by Django 5.1 on 2024-09-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0007_produit_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transation",
            name="prix_unitaire",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="transation",
            name="qt_trans",
            field=models.IntegerField(),
        ),
    ]
