# Generated by Django 5.1 on 2024-08-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('phone', models.FloatField(blank=True, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.FloatField(blank=True, max_length=50)),
                ('prix', models.FloatField(default=0)),
                ('qt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('date_fact', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.client')),
            ],
        ),
        migrations.CreateModel(
            name='Transation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_trans', models.IntegerField(default=0)),
                ('date_trans', models.DateField(auto_now_add=True)),
                ('prix_unitaire', models.FloatField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
            ],
        ),
    ]
