# Generated by Django 5.1 on 2024-08-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('pu', models.FloatField(default=0)),
                ('qt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('date', models.DateField()),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTrans', models.DateField()),
                ('pU', models.FloatField(default=0)),
                ('qt', models.FloatField(default=0)),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.clients')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.produit')),
            ],
        ),
    ]
