# Generated by Django 5.1 on 2024-08-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('phone', models.FloatField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='facture',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='produit',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='date',
            new_name='date_fact',
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facturation.client'),
        ),
        migrations.CreateModel(
            name='Transation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_trans', models.IntegerField(default=0)),
                ('date_trans', models.DateField()),
                ('prix_unitaire', models.FloatField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.facture')),
                ('produit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='facturation.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
