# Generated by Django 5.1 on 2024-09-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_client_remove_facture_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
