# Generated by Django 5.1 on 2024-09-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_alter_facture_date_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
