# Generated by Django 5.1 on 2024-09-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_alter_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/Produit'),
        ),
    ]
