# Generated by Django 5.1 on 2024-09-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0006_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transation',
            name='date_trans',
            field=models.DateField(auto_now_add=True),
        ),
    ]
