# Generated by Django 5.1 on 2025-03-25 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_alter_transation_date_trans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produit',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transation',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transation',
            name='prix_unitaire',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transation',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturation.produit'),
        ),
        migrations.AlterField(
            model_name='transation',
            name='qt_trans',
            field=models.IntegerField(),
        ),
    ]
